apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydeploy
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydeploy
    spec:
      containers:
      - image: devops_pipeline_demo
        name: devops-pipeline-demo-cdmqf
        ports:
        - containerPort: 80
        resources: {}
   ifNotPresent: 'IfNotPresent'
status: {}
